## PYTHON DATA TYPES

In [2]:
# PYTHON DATA TYPES
5 

5

In [3]:
a

NameError: name 'a' is not defined

In [4]:
type(5)

int

In [5]:
# Numeric Data Type
# 1. Int 2. Float 3. Complex

In [6]:
# INTEGER
type(0)

int

In [7]:
type(-3)

int

In [8]:
# FLOAT
type(3.14)

float

In [9]:
type(0.0)

float

In [10]:
print(6)

6


In [11]:
print('Hello, World')

Hello, World


In [12]:
type('Hello, World')

str

In [13]:
# COMPLEX DATA TYPE
a = 2 + 3j
type(a)

complex

In [14]:
input()

''

In [15]:
int(input())

ValueError: invalid literal for int() with base 10: ''

In [16]:
int(input())

ValueError: invalid literal for int() with base 10: ''

In [17]:
input("Enter Password: ").upper()

Enter Password: 


''

In [18]:
a = 3

In [19]:
a

3

In [20]:
3 == 3

True

In [21]:
3 != 3

False

In [22]:
# Write a program that ask the users to put their age and verify the age data type
# Write a program that calculate the average of 3 numbers

In [23]:
a = int(input("Enter your age: "))
print(a)
type(a)

Enter your age: 


ValueError: invalid literal for int() with base 10: ''

In [24]:
x = (5+6+10)/3
print(x)

7.0


In [25]:
x = float(input("Enter value for x: "))
y = float(input("Enter value for y: "))
z = float(input("Enter value for z: "))

avg = round((x + y + z)/3,2)
print(avg)

Enter value for x: 


ValueError: could not convert string to float: ''

In [26]:
x = float(input("Enter value for x: "))
y = float(input("Enter value for y: "))
z = float(input("Enter value for z: "))

avg = round((x + y + z)/3,2)
print(f"The average of {x}, {y}, and {z} is {avg}")

Enter value for x: 1.2
Enter value for y: 3.4
Enter value for z: 6.7
The average of 1.2, 3.4, and 6.7 is 3.77


In [27]:
x

1.2

In [18]:
# PROGRAM TO CALCULATE THE AREA OF A CIRCLE, GETTING THE RADIUS FROM THE USER AND A FLOATTING VALUE, WHERE pi = 3.14
# where area_of_circle = pi * r**2

# SOLUTION
pi = 3.14
r = float(input("Enter radius: "))
area_of_circle = pi * r**2
print(area_of_circle)

Enter radius: 2
12.56


In [9]:
import math as mth

In [10]:
dir(mth)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [11]:
mth.pi

3.141592653589793

In [12]:
mth.sqrt(25)

5.0

In [13]:
mth.factorial(4)

24

In [19]:
mth.pow(r,2)

4.0

In [17]:
# mth.pow(3,2) 
3**2

9

In [20]:
import pandas as pd
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '

In [1]:
import math as mth

In [4]:
r = 3
area = round(mth.pi * mth.pow(r,2),2)
print(area)

28.27


### VARIABLES

##### -- A VARIABLE IS A CONTAINER WHERE VALUES ARE STORED. 

#### RULES FOR CREATING A VARIABLE

In [6]:
# 1. Variable can contain a single letter and also a word
a = 10

In [7]:
a

10

In [8]:
name = "UptraxTech"

In [9]:
name

'UptraxTech'

In [11]:
# 2. No varaibles should start with a number or any special character,\
# except special characters like the underscore (_)

_3 = 3

In [12]:
_3

3

In [20]:
# 3. It is not advisable to use a python keyword as a variable e.g print, type, round, sum!
sum_num = 4
sum_num

4

In [17]:
sum_num = 2


In [19]:
sum_num

2

In [22]:
# note that age is not the same as Age, and AGE, AGe
a

10

In [23]:
A

NameError: name 'A' is not defined

#### TYPES OF VARIABLES

In [25]:
# 1. Camel Case
# 2. Pascal Case
# 3. Snake Case -- Most recommended

In [27]:
# Write a program that returns the average of two floating values from the user!
first_floating_number = float(input("Enter first floating value: "))
second_floating_number = float(input("Enter second floating value: "))
average = round((first_floating_number + second_floating_number)/2,2)
average

Enter first floating value: 2.4
Enter second floating value: 2.8


2.6

## DATA TYPES CONTD

In [28]:
type(4) # integer

int

In [29]:
type(2.0) # Float

float

In [30]:
type(2 + 3j) # Complex

complex

#### STRING (str)

In [31]:
type('1234')

str

In [32]:
type("Tech")

str

In [33]:
type("""Prosper""")

str

In [34]:
type('''PH''')

str

In [36]:
str(input())

Prosper


'Prosper'

#### SEQUENTIAL DATA-TYPE

In [5]:
# lIST - is an ordered collection of items enclosed within a square bracket [].
animals = ["dog", "goat", "camel", "snake", "lion", "cat"]
type(animals)

list

In [42]:
animals

['dog', 'goat', 'camel', 'snake', 'lion', 'cat']

In [43]:
# List are immutable
animals.remove("cat")

In [44]:
animals

['dog', 'goat', 'camel', 'snake', 'lion']

In [46]:
animals.append("Tiger")

In [47]:
animals

['dog', 'goat', 'camel', 'snake', 'lion', 'Tiger']

In [1]:
num = [1,2,3,4,5]
type(num)

list

In [2]:
# List are Index values
print(3)

3


In [3]:
for number in range(10):
    print(number)

0
1
2
3
4
5
6
7
8
9


In [6]:
print(animals)

['dog', 'goat', 'camel', 'snake', 'lion', 'cat']


In [7]:
animals[0]

'dog'

In [8]:
animals[4]

'lion'

In [9]:
animals[:2]

['dog', 'goat']

In [10]:
animals[3:]

['snake', 'lion', 'cat']

In [11]:
animals[-1]

'cat'

In [12]:
## TUPLE, () or ordered values seperated with a comma (,) 
number = 1,2.3,3,2 + 3j, "data analysis"
type(number)

tuple

In [13]:
print(type(number))

<class 'tuple'>


In [14]:
fruits = ("Orange", "Cherry", "Mango", "Water Melon", "Pineapple")
type(fruits)

tuple

In [15]:
print(fruits[0])

Orange


In [17]:
fruits[3:]

('Water Melon', 'Pineapple')

In [22]:
fruits.remove("Orange") # Since Tuple is mutable, you cannot append or remove

AttributeError: 'tuple' object has no attribute 'remove'

In [23]:
## BOOLEAN DATA TYPE
type(False)

bool

In [24]:
type(True)

bool

In [25]:
True + 2 

3

In [26]:
False - 1

-1

In [27]:
False + False 

0

In [28]:
True * True

1

In [31]:
## SET are unordered collection of items enclosed within a braces or curly bracket {}
numbers = {1,1,1,2,2,2,3,4,5,6}
type(numbers)

set

In [32]:
numbers.add(10)

In [33]:
numbers

{1, 2, 3, 4, 5, 6, 10}

In [34]:
numbers[0]

TypeError: 'set' object is not subscriptable

## CONTROL FLOW IN PYTHON

In [ ]:
# CONDITIONAL FLOW (IF, ELIF, ELSE)

number = int(input("Enter a number: "))
if number < 10:
    print(f"{number} is less than 10")
else:
    print(f"{number} is greater than 10")

# Python for Data Analysis

In [2]:
# Numerical python - NUMPY
# Pandas
# Seaborn
# Matplotlib.pyplot

In [3]:
# NUMERICAL PYTHON - NUMPY take in list of numbers in form array and matrix. 
# Contains mathematical and statistical functions 

import numpy as np
dir(np)


['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [4]:
items = [1.2, 3, "Data", False, 2 + 3j]
type(items)

list

In [5]:
item = (1.2, 3, "Data", False, 2 + 3j)
type(item)

tuple

In [6]:
items

[1.2, 3, 'Data', False, (2+3j)]

In [7]:
items[1]

3

In [8]:
items[2]

'Data'

In [9]:
items[0]

1.2

In [10]:
print(items)

[1.2, 3, 'Data', False, (2+3j)]


In [15]:
type(items[4])

complex

In [22]:
import numpy as np

In [23]:
# 1D array
a = np.array([1,2,3])
print(a)
print(type(a))
a.ndim

[1 2 3]
<class 'numpy.ndarray'>


1

In [30]:
# 2D array
b = np.array([[1,2,3], [4,5,6]])
print(b)
b.ndim
b.shape
b.size
b.dtype  # numpy properties

[[1 2 3]
 [4 5 6]]


dtype('int32')

In [27]:
# array of zeros
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
# array of ones
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
# Numpy Indexing and Slicing

In [31]:
numbers = np.array([1,2,3,4,5,6,7,8]) 
print(numbers[:2])

[1 2]


In [32]:
print(numbers[4:])

[5 6 7 8]


In [35]:
# Aggregations and Statistics in Numpy
agg = np.array([1,2,3,4,5,6,7,8])
print(np.sum(agg))
print(np.mean(agg))
print(np.std(agg))
print(np.max(agg))
print(np.min(agg))

36
4.5
2.29128784747792
8
1


In [57]:
x = np.array([[1,2,3], [4,5,6]])
print(x)
x.ndim

[[1 2 3]
 [4 5 6]]


2

In [58]:
# Reshape x
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
y = x.reshape(2,3)

In [61]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
y.shape

(3, 2)

In [50]:
a = [1,2,3]
b = [4,5,6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [51]:
# Array Operations
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x + y)

[5 7 9]


In [52]:
print(x - y)
print(x * y)

[-3 -3 -3]
[ 4 10 18]


## PANDAS 

### Pandas is a powerful and widely used Python library for data manipulation and analysis.
### It provides two primary data structures
### 1. Pandas Series - One-dimensional labeled array (Like a column in MS Excel)
### 2. Pandas Dataframe  - Two dimensional labeled data structire (like a table or spreadsheet)

## Key Features of Pandas 
### 1. Easy handling of missing values and duplicates
### 2. Powerful Grouping and aggregation
### 3. Labeled-based indexing and slicing
### 4. Data Alignment and reshaping
### 5. Built-in tools for reading and writing data e.g CSV, Excel files, SQL, SPSS etc
### 6. Integrate with Numpy, Matplotlib, Seaborn, Scikit-learn etc

In [63]:
import pandas as pd 
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '

In [68]:
data = pd.read_excel(r"C:\Users\Molly\Desktop\class documents\outlet_sales.xlsx")

In [69]:
data

Date  Day     Month  Year  Customer_Age       Age_Group  \
0      2013-11-26   26  November  2013            19     Youth (<25)   
1      2015-11-26   26  November  2015            19     Youth (<25)   
2      2014-03-23   23     March  2014            49  Adults (35-64)   
3      2016-03-23   23     March  2016            49  Adults (35-64)   
4      2014-05-15   15       May  2014            47  Adults (35-64)   
...           ...  ...       ...   ...           ...             ...   
112031 2016-04-12   12     April  2016            41  Adults (35-64)   
112032 2014-04-02    2     April  2014            18     Youth (<25)   
112033 2016-04-02    2     April  2016            18     Youth (<25)   
112034 2014-03-04    4     March  2014            37  Adults (35-64)   
112035 2016-03-04    4     March  2016            37  Adults (35-64)   

       Customer_Gender         Country             State Product_Category  \
0                    M          Canada  British Columbia      Accessories   
1                    M          Canada  British Columbia      Accessories   
2                    M       Australia   New South Wales      Accessories   
3                    M       Australia   New South Wales      Accessories   
4                    F       Australia   New South Wales      Accessories   
...                ...             ...               ...              ...   
112031               M  United Kingdom           England         Clothing   
112032               M       Australia        Queensland         Clothing   
112033               M       Australia        Queensland         Clothing   
112034               F          France     Seine (Paris)         Clothing   
112035               F          France     Seine (Paris)         Clothing   

       Sub_Category              Product  Order_Quantity  Unit_Cost  \
0        Bike Racks  Hitch Rack - 4-Bike               8         45   
1        Bike Racks  Hitch Rack - 4-Bike               8         45   
2        Bike Racks  Hitch Rack - 4-Bike              23         45   
3        Bike Racks  Hitch Rack - 4-Bike              20         45   
4        Bike Racks  Hitch Rack - 4-Bike               4         45   
...             ...                  ...             ...        ...   
112031        Vests      Classic Vest, S               3         24   
112032        Vests      Classic Vest, M              22         24   
112033        Vests      Classic Vest, M              22         24   
112034        Vests      Classic Vest, L              24         24   
112035        Vests      Classic Vest, L              23         24   

        Unit_Price  Profit  Cost  Revenue  
0              120     590   360      950  
1              120     590   360      950  
2              120    1366  1035     2401  
3              120    1188   900     2088  
4              120     238   180      418  
...            ...     ...   ...      ...  
112031          64     112    72      184  
112032          64     655   528     1183  
112033          64     655   528     1183  
112034          64     684   576     1260  
112035          64     655   552     1207  

[112036 rows x 18 columns]

In [70]:
data.head()

Date  Day     Month  Year  Customer_Age       Age_Group  \
0 2013-11-26   26  November  2013            19     Youth (<25)   
1 2015-11-26   26  November  2015            19     Youth (<25)   
2 2014-03-23   23     March  2014            49  Adults (35-64)   
3 2016-03-23   23     March  2016            49  Adults (35-64)   
4 2014-05-15   15       May  2014            47  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   
3               M  Australia   New South Wales      Accessories   Bike Racks   
4               F  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike               8         45         120     590   360   
1  Hitch Rack - 4-Bike               8         45         120     590   360   
2  Hitch Rack - 4-Bike              23         45         120    1366  1035   
3  Hitch Rack - 4-Bike              20         45         120    1188   900   
4  Hitch Rack - 4-Bike               4         45         120     238   180   

   Revenue  
0      950  
1      950  
2     2401  
3     2088  
4      418